export {Footer} from './Footer'
export {Header} from './Header'
export {CookieMessage} from './CookieMessage'
export {FAQ} from './FAQ'
export {HeaderLink} from './HeaderLink'
export {HowChooseAPhotoSection} from './HowChooseAPhotoSection'
export {PurchaseQuestionSection} from './PurchaseQuestionSection'
export {SDEK} from './SDEK'
