export {Navbar} from './Navbar'
export {Content} from './Content'
export {PromocodeForm} from './PromocodeForm'
export {TestimonialForm} from './TestimonialForm'
export {FAQForm} from './FAQForm'
export {LanguageForm} from './LanguageForm'
export {SectionForm} from './SectionForm'
export {PromoPictureForm} from './PromoPictureForm'
